# Generated by Django 3.0.5 on 2021-10-09 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True)),
                ('Juzgado', models.CharField(blank=True, max_length=150)),
                ('Observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(blank=True, max_length=80)),
                ('Num_documento', models.CharField(blank=True, max_length=12)),
                ('Num_celular', models.CharField(blank=True, max_length=12)),
                ('Correo', models.CharField(blank=True, max_length=40)),
                ('Direccion', models.CharField(blank=True, max_length=60)),
                ('Observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Documental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_doc', models.DateField(null=True)),
                ('Cant_hojas', models.IntegerField()),
                ('Descripcion1', models.CharField(max_length=150, null=True)),
                ('Descripcion2', models.CharField(max_length=150, null=True)),
                ('Descripcion3', models.CharField(max_length=150, null=True)),
                ('Guardada_en', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_evento', models.DateField(null=True)),
                ('Descripcion1', models.CharField(max_length=150, null=True)),
                ('Descripcion2', models.CharField(max_length=150, null=True)),
                ('Descripcion3', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_pago', models.DateField(null=True)),
                ('Tip_pag', models.CharField(blank=True, choices=[('1', 'Honrario'), ('2', 'Tasa'), ('3', 'Gasto')], max_length=8)),
                ('Monto_acordado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Pago_parcial', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cabogado', models.BooleanField()),
                ('Tasas', models.BooleanField()),
                ('Derecho_archivo', models.BooleanField()),
                ('Ser_parte', models.BooleanField()),
                ('Dig_demanda', models.BooleanField()),
                ('Crear_exp', models.BooleanField()),
                ('Doc_24hs', models.BooleanField()),
                ('Oficio_control', models.CharField(blank=True, max_length=150)),
                ('Pridec_coptra', models.BooleanField()),
                ('Pridec_cedpos', models.BooleanField()),
                ('Observacion', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Expedien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipexp', models.CharField(blank=True, choices=[('1', 'Exp'), ('2', 'Inc'), ('3', 'Otro')], max_length=4)),
                ('Numeroexp', models.CharField(blank=True, max_length=20)),
                ('Caratula', models.CharField(max_length=80, null=True)),
                ('Resumen_caso', models.CharField(blank=True, max_length=150)),
                ('Activo', models.BooleanField()),
                ('Prioridad', models.BooleanField()),
                ('Fecha_aud', models.DateField(null=True)),
                ('Observacion', models.CharField(blank=True, max_length=150)),
                ('Audiencia_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Audiencia')),
                ('Cliente_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Cliente')),
                ('Documental_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Documental')),
                ('Evento_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Evento')),
                ('Pagos_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Pagos')),
                ('Tramite_exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Tramite')),
            ],
        ),
    ]
