# Generated by Django 3.0.5 on 2021-10-09 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsisexp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedien',
            name='Audiencia_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Audiencia'),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Cliente_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Cliente'),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Documental_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Documental'),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Evento_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Evento'),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Fecha_aud',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Pagos_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Pagos'),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Tramite_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Tramite'),
        ),
    ]
