# Generated by Django 3.0.5 on 2023-01-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsisexp', '0003_auto_20211031_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedien',
            name='Fecha_aud',
        ),
        migrations.AddField(
            model_name='expedien',
            name='Juzgadoexp',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='expedien',
            name='Resumen_caso',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
