# Generated by Django 3.0.5 on 2023-01-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsisexp', '0006_remove_pagos_otro_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='otro_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
