# Generated by Django 3.0.5 on 2023-01-03 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsisexp', '0007_pagos_otro_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(null=True)),
                ('tipo_prueba', models.CharField(blank=True, max_length=150)),
                ('Observacion', models.CharField(blank=True, max_length=150)),
                ('Pruebas_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appsisexp.Expedien')),
            ],
        ),
    ]
