# Generated by Django 3.0.5 on 2023-01-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsisexp', '0009_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='Hora_turno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='Nombre',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='turno',
            name='Nro_celular',
            field=models.CharField(blank=True, default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='Onservacion',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turno',
            name='Tema',
            field=models.CharField(blank=True, default=0, max_length=150),
            preserve_default=False,
        ),
    ]
